CREATE TABLE PRODUCT(id INTEGER PRIMARY KEY autoincrement, name TEXT, purine_acid_value TEXT);

insert into PRODUCT(name, purine_acid_value) values ('Cukier', 0);
insert into PRODUCT(name, purine_acid_value) values ('Margaryny', 0);
insert into PRODUCT(name, purine_acid_value) values ('Masło', 0);
insert into PRODUCT(name, purine_acid_value) values ('Miód', 0);
insert into PRODUCT(name, purine_acid_value) values ('Oleje roślinne', 0);
insert into PRODUCT(name, purine_acid_value) values ('Oliwa z oliwek', 0);
insert into PRODUCT(name, purine_acid_value) values ('Majonez', 1);
insert into PRODUCT(name, purine_acid_value) values ('Jajka, białko', 2);
insert into PRODUCT(name, purine_acid_value) values ('Mleko kokosowe', 2);
insert into PRODUCT(name, purine_acid_value) values ('Jajka', 5);
insert into PRODUCT(name, purine_acid_value) values ('Sok pomidorowy', 5);
insert into PRODUCT(name, purine_acid_value) values ('Sok z marchwi', 5);
insert into PRODUCT(name, purine_acid_value) values ('Syrop klonowy', 5);
insert into PRODUCT(name, purine_acid_value) values ('Ser Brie', 7);
insert into PRODUCT(name, purine_acid_value) values ('Sery pleśniowe', 7);
insert into PRODUCT(name, purine_acid_value) values ('Jogurt (3,5% tłuszczu)', 8);
insert into PRODUCT(name, purine_acid_value) values ('Mleko zsiadłe', 8);
insert into PRODUCT(name, purine_acid_value) values ('Piwo, bezalkoholowe', 8);
insert into PRODUCT(name, purine_acid_value) values ('Mleko', 8);
insert into PRODUCT(name, purine_acid_value) values ('Cola', 10);
insert into PRODUCT(name, purine_acid_value) values ('Piwo pszeniczne (crystal)', 10);
insert into PRODUCT(name, purine_acid_value) values ('Ser Mozzarella', 10);
insert into PRODUCT(name, purine_acid_value) values ('Ser Parmezan', 10);
insert into PRODUCT(name, purine_acid_value) values ('Serek wiejski, ziarnisty', 10);
insert into PRODUCT(name, purine_acid_value) values ('Sok grejpfrutowy', 10);
insert into PRODUCT(name, purine_acid_value) values ('Twaróg', 10);
insert into PRODUCT(name, purine_acid_value) values ('Ananas', 12);
insert into PRODUCT(name, purine_acid_value) values ('Gruszka', 12);
insert into PRODUCT(name, purine_acid_value) values ('Kaki', 12);
insert into PRODUCT(name, purine_acid_value) values ('Mango', 12);
insert into PRODUCT(name, purine_acid_value) values ('Papaja', 12);
insert into PRODUCT(name, purine_acid_value) values ('Rabarbar', 12);
insert into PRODUCT(name, purine_acid_value) values ('Sok jabłkowy', 12);
insert into PRODUCT(name, purine_acid_value) values ('Sok pomarańczowy', 12);
insert into PRODUCT(name, purine_acid_value) values ('Piwo typu lager', 13);
insert into PRODUCT(name, purine_acid_value) values ('Ser topiony 60% tłuszczu', 13);
insert into PRODUCT(name, purine_acid_value) values ('Żurawina', 13);
insert into PRODUCT(name, purine_acid_value) values ('Chleb biały, pszeniczny', 14);
insert into PRODUCT(name, purine_acid_value) values ('Jabłko', 14);
insert into PRODUCT(name, purine_acid_value) values ('Grejpfrut', 15);
insert into PRODUCT(name, purine_acid_value) values ('Jeżyna', 15);
insert into PRODUCT(name, purine_acid_value) values ('Agrest', 16);
insert into PRODUCT(name, purine_acid_value) values ('Ser Gouda', 16);
insert into PRODUCT(name, purine_acid_value) values ('Sok multiwitamina', 16);
insert into PRODUCT(name, purine_acid_value) values ('Cytryna', 17);
insert into PRODUCT(name, purine_acid_value) values ('Kurki', 17);
insert into PRODUCT(name, purine_acid_value) values ('Porzeczka czerwona', 17);
insert into PRODUCT(name, purine_acid_value) values ('Sery żółte', 17);
insert into PRODUCT(name, purine_acid_value) values ('Śliwki mirabelki', 17);
insert into PRODUCT(name, purine_acid_value) values ('Maliny', 18);
insert into PRODUCT(name, purine_acid_value) values ('Arbuz', 19);
insert into PRODUCT(name, purine_acid_value) values ('Czereśnie', 19);
insert into PRODUCT(name, purine_acid_value) values ('Kiwi', 19);
insert into PRODUCT(name, purine_acid_value) values ('Pomarańcza', 19);
insert into PRODUCT(name, purine_acid_value) values ('Wiśnie', 19);
insert into PRODUCT(name, purine_acid_value) values ('Jagody', 20);
insert into PRODUCT(name, purine_acid_value) values ('Morele', 20);
insert into PRODUCT(name, purine_acid_value) values ('Brzoskwinia', 21);
insert into PRODUCT(name, purine_acid_value) values ('Truskawki', 21);
insert into PRODUCT(name, purine_acid_value) values ('Bułka kajzerka*', 22);
insert into PRODUCT(name, purine_acid_value) values ('Orzechy brazylijskie', 22);
insert into PRODUCT(name, purine_acid_value) values ('Piwo jasne*', 24);
insert into PRODUCT(name, purine_acid_value) values ('Śliwki', 24);
insert into PRODUCT(name, purine_acid_value) values ('Kaszka kukurydziana', 25);
insert into PRODUCT(name, purine_acid_value) values ('Czekolada gorzka', 26);
insert into PRODUCT(name, purine_acid_value) values ('Skórka pomarańczowa', 26);
insert into PRODUCT(name, purine_acid_value) values ('Orzechy włoskie', 27);
insert into PRODUCT(name, purine_acid_value) values ('Winogrona', 27);
insert into PRODUCT(name, purine_acid_value) values ('Piwo tradycyjne brytyjskie', 27);
insert into PRODUCT(name, purine_acid_value) values ('Grzyby konserwowe', 29);
insert into PRODUCT(name, purine_acid_value) values ('Pigwa', 30);
insert into PRODUCT(name, purine_acid_value) values ('Ser Feta', 30);
insert into PRODUCT(name, purine_acid_value) values ('Smardze', 30);
insert into PRODUCT(name, purine_acid_value) values ('Czarny bez', 33);
insert into PRODUCT(name, purine_acid_value) values ('Melon*', 33);
insert into PRODUCT(name, purine_acid_value) values ('Daktyl, suszony*', 35);
insert into PRODUCT(name, purine_acid_value) values ('Migdały', 37);
insert into PRODUCT(name, purine_acid_value) values ('Orzechy laskowe*', 37);
insert into PRODUCT(name, purine_acid_value) values ('Żelatyna', 37);
insert into PRODUCT(name, purine_acid_value) values ('Chleb pszenny', 40);
insert into PRODUCT(name, purine_acid_value) values ('Makaron pszeniczny*', 40);
insert into PRODUCT(name, purine_acid_value) values ('Mąka pszenna typ 405', 40);
insert into PRODUCT(name, purine_acid_value) values ('Chleb lniany', 45);
insert into PRODUCT(name, purine_acid_value) values ('Chleb żytni', 45);
insert into PRODUCT(name, purine_acid_value) values ('Bułka tarta', 48);
insert into PRODUCT(name, purine_acid_value) values ('Bazylia', 50);
insert into PRODUCT(name, purine_acid_value) values ('Boczniaki*', 50);
insert into PRODUCT(name, purine_acid_value) values ('Chleb pełnoziarnisty', 50);
insert into PRODUCT(name, purine_acid_value) values ('Chleb razowy', 50);
insert into PRODUCT(name, purine_acid_value) values ('Marcepan', 50);
insert into PRODUCT(name, purine_acid_value) values ('Żyto (pełne ziarno)', 51);
insert into PRODUCT(name, purine_acid_value) values ('Banan*', 57);
insert into PRODUCT(name, purine_acid_value) values ('Pieczarki*', 58);
insert into PRODUCT(name, purine_acid_value) values ('Suchary*', 60);
insert into PRODUCT(name, purine_acid_value) values ('Czekolada mleczna', 60);
insert into PRODUCT(name, purine_acid_value) values ('Jabłko suszone*', 60);
insert into PRODUCT(name, purine_acid_value) values ('Ketchup*', 60);
insert into PRODUCT(name, purine_acid_value) values ('Pieczywo chrupkie*', 60);
insert into PRODUCT(name, purine_acid_value) values ('Raki*', 60);
insert into PRODUCT(name, purine_acid_value) values ('Sos sojowy*', 60);
insert into PRODUCT(name, purine_acid_value) values ('Sezam, nasiona suszone*', 63);
insert into PRODUCT(name, purine_acid_value) values ('Figi suszone', 64);
insert into PRODUCT(name, purine_acid_value) values ('Płatki kukurydziane', 64);
insert into PRODUCT(name, purine_acid_value) values ('Śliwki suszone', 64);
insert into PRODUCT(name, purine_acid_value) values ('Tofu', 70);
insert into PRODUCT(name, purine_acid_value) values ('Mielonka', 70);
insert into PRODUCT(name, purine_acid_value) values ('Kakao w proszku', 71);
insert into PRODUCT(name, purine_acid_value) values ('Mąka ryżowa', 72);
insert into PRODUCT(name, purine_acid_value) values ('Kiełbasa biała', 73);
insert into PRODUCT(name, purine_acid_value) values ('Morele suszone', 73);
insert into PRODUCT(name, purine_acid_value) values ('Metka*', 74);
insert into PRODUCT(name, purine_acid_value) values ('Ośmiornica', 77);
insert into PRODUCT(name, purine_acid_value) values ('Lin*', 80);
insert into PRODUCT(name, purine_acid_value) values ('Orzeszki ziemne*', 80);
insert into PRODUCT(name, purine_acid_value) values ('Węgorz wędzony', 80);
insert into PRODUCT(name, purine_acid_value) values ('Sago', 82);
insert into PRODUCT(name, purine_acid_value) values ('Mąka pszenna typ 1700', 84);
insert into PRODUCT(name, purine_acid_value) values ('Mąka razowa', 84);
insert into PRODUCT(name, purine_acid_value) values ('Proso', 85);
insert into PRODUCT(name, purine_acid_value) values ('Frankfuterki*', 89);
insert into PRODUCT(name, purine_acid_value) values ('Tapioka', 89);
insert into PRODUCT(name, purine_acid_value) values ('Ostrygi', 90);
insert into PRODUCT(name, purine_acid_value) values ('Wołowina, mostek*', 90);
insert into PRODUCT(name, purine_acid_value) values ('Kiełbasa smażona cielęca', 91);
insert into PRODUCT(name, purine_acid_value) values ('Parówki*', 91);
insert into PRODUCT(name, purine_acid_value) values ('Borowik szlachetny*', 92);
insert into PRODUCT(name, purine_acid_value) values ('Boczek', 96);
insert into PRODUCT(name, purine_acid_value) values ('Jęczmień', 96);
insert into PRODUCT(name, purine_acid_value) values ('Mortadela*', 97);
insert into PRODUCT(name, purine_acid_value) values ('Musztarda', 100);
insert into PRODUCT(name, purine_acid_value) values ('Owies (nasiona bez łuski)', 100);
insert into PRODUCT(name, purine_acid_value) values ('Salami*', 103);
insert into PRODUCT(name, purine_acid_value) values ('Królik', 105);
insert into PRODUCT(name, purine_acid_value) values ('Zając*', 105);
insert into PRODUCT(name, purine_acid_value) values ('Rodzynki', 108);
insert into PRODUCT(name, purine_acid_value) values ('Dorsz*', 109);
insert into PRODUCT(name, purine_acid_value) values ('Dorsz*', 109);
insert into PRODUCT(name, purine_acid_value) values ('Kurczak, nóżki, ze skórą*', 110);
insert into PRODUCT(name, purine_acid_value) values ('Paluszki rybne, mrożone', 110);
insert into PRODUCT(name, purine_acid_value) values ('Sandacz*', 110);
insert into PRODUCT(name, purine_acid_value) values ('Wołowina, łopatka', 110);
insert into PRODUCT(name, purine_acid_value) values ('Wołowina, polędwica', 110);
insert into PRODUCT(name, purine_acid_value) values ('Wołowina, rostbef*', 110);
insert into PRODUCT(name, purine_acid_value) values ('Homar', 118);
insert into PRODUCT(name, purine_acid_value) values ('Wołowina, antrykot', 120);
insert into PRODUCT(name, purine_acid_value) values ('Wołowina, karkówka*', 120);
insert into PRODUCT(name, purine_acid_value) values ('Szynka gotowana wieprzowa*', 130);
insert into PRODUCT(name, purine_acid_value) values ('Sola*', 131);
insert into PRODUCT(name, purine_acid_value) values ('Wieprzowina, ozory', 136);
insert into PRODUCT(name, purine_acid_value) values ('Kaczka', 138);
insert into PRODUCT(name, purine_acid_value) values ('Sarnina, udziec', 138);
insert into PRODUCT(name, purine_acid_value) values ('Łupacz', 139);
insert into PRODUCT(name, purine_acid_value) values ('Cielęcina, polędwica', 140);
insert into PRODUCT(name, purine_acid_value) values ('Jagnięcina*', 140);
insert into PRODUCT(name, purine_acid_value) values ('Szczupak*', 140);
insert into PRODUCT(name, purine_acid_value) values ('Słonecznik, nasiona*', 143);
insert into PRODUCT(name, purine_acid_value) values ('Kawior', 144);
insert into PRODUCT(name, purine_acid_value) values ('Makrela*', 145);
insert into PRODUCT(name, purine_acid_value) values ('Wieprzowina, karkówka*', 145);
insert into PRODUCT(name, purine_acid_value) values ('Cielęcina, płucka', 147);
insert into PRODUCT(name, purine_acid_value) values ('Krewetki*', 147);
insert into PRODUCT(name, purine_acid_value) values ('Kraby', 148);
insert into PRODUCT(name, purine_acid_value) values ('Gryka (ziarno)', 149);
insert into PRODUCT(name, purine_acid_value) values ('Bażant', 150);
insert into PRODUCT(name, purine_acid_value) values ('Cielęcina, łopatka*', 150);
insert into PRODUCT(name, purine_acid_value) values ('Indyk, ze skórą', 150);
insert into PRODUCT(name, purine_acid_value) values ('Wieprzowina, łopatka', 150);
insert into PRODUCT(name, purine_acid_value) values ('Wieprzowina, polędwica', 150);
insert into PRODUCT(name, purine_acid_value) values ('Karp*', 160);
insert into PRODUCT(name, purine_acid_value) values ('Okoń', 160);
insert into PRODUCT(name, purine_acid_value) values ('Wieprzowina, golonka', 160);
insert into PRODUCT(name, purine_acid_value) values ('Wieprzowina, szynka*', 160);
insert into PRODUCT(name, purine_acid_value) values ('Wołowina, ozory', 160);
insert into PRODUCT(name, purine_acid_value) values ('Gęś*', 165);
insert into PRODUCT(name, purine_acid_value) values ('Kaszanka „Wątrobianka”*', 166);
insert into PRODUCT(name, purine_acid_value) values ('Łosoś*', 170);
insert into PRODUCT(name, purine_acid_value) values ('Mak', 170);
insert into PRODUCT(name, purine_acid_value) values ('Kurczak, piersi ze skórą*', 175);
insert into PRODUCT(name, purine_acid_value) values ('Halibut', 178);
insert into PRODUCT(name, purine_acid_value) values ('Konina', 200);
insert into PRODUCT(name, purine_acid_value) values ('Śledź*', 210);
insert into PRODUCT(name, purine_acid_value) values ('Cielęcina, nerki', 218);
insert into PRODUCT(name, purine_acid_value) values ('Cielęcina, wątróbka*', 218);
insert into PRODUCT(name, purine_acid_value) values ('Anchois', 240);
insert into PRODUCT(name, purine_acid_value) values ('Karmazyn', 240);
insert into PRODUCT(name, purine_acid_value) values ('Kminek', 240);
insert into PRODUCT(name, purine_acid_value) values ('Jagnięcina, serca', 241);
insert into PRODUCT(name, purine_acid_value) values ('Wołowina, serca', 256);
insert into PRODUCT(name, purine_acid_value) values ('Tuńczyk', 257);
insert into PRODUCT(name, purine_acid_value) values ('Wołowina, nerki', 269);
insert into PRODUCT(name, purine_acid_value) values ('Pstrąg*', 297);
insert into PRODUCT(name, purine_acid_value) values ('Wieprzowina, nerki', 334);
insert into PRODUCT(name, purine_acid_value) values ('Sardynki *', 345);
insert into PRODUCT(name, purine_acid_value) values ('Wołowina, płucka', 399);
insert into PRODUCT(name, purine_acid_value) values ('Cielęcina, mózg', 460);
insert into PRODUCT(name, purine_acid_value) values ('Wieprzowina, wątróbka*', 515);
insert into PRODUCT(name, purine_acid_value) values ('Wołowina, wątróbka*', 554);
insert into PRODUCT(name, purine_acid_value) values ('Drożdże do pieczenia', 680);
insert into PRODUCT(name, purine_acid_value) values ('Szprotki wędzone*', 804);
insert into PRODUCT(name, purine_acid_value) values ('Cielęcina, nerkówka', 1260);
insert into PRODUCT(name, purine_acid_value) values ('Drożdże piwne', 1810);